# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x121316ff
bordercolor = 0x8d9199ff
focuscolor = 0xa0caffff
maximizescreencolor = 0xbbc7dbff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xd7bde4ff
globalcolor = 0x00497eff
overlaycolor = 0x3c4858ff
