# Noctalia Theme for Mango
# Generated automatically by Noctalia Shell

shadowscolor = 0x000000ff
rootcolor = 0x131316ff
bordercolor = 0x918f9aff
focuscolor = 0xbfc2ffff
maximizescreencolor = 0xc5c4ddff
urgentcolor = 0xffb4abff
scratchpadcolor = 0xe8b9d5ff
globalcolor = 0x383e8fff
overlaycolor = 0x444559ff
